# @package _global_
xpd: ???

domain: ???

xp_overrides: 
  datamodule:
    input_da:
      _target_: src.utils.load_enatl
    domains:
      train:
        time: {_target_: builtins.slice , _args_: ['2010-02-24', '2010-07-3']}
      val: 
        time: {_target_: builtins.slice, _args_: ['2009-12-15', '2010-02-24']}
      test: 
        time: {_target_: builtins.slice,  _args_: ['2009-07-01', '2009-12-20']}
    xrds_kw: 
      strides: {lat: 200, lon: 200}
      domain_limits: ${domain.train}

trainer: 
  _target_: pytorch_lightning.Trainer
  inference_mode: False
  accelerator: gpu
  devices: 1
  logger: False

lit_mod: 
  _target_: contrib.multi_domain_diag.load_cfg_from_xp
  key: model
  xpd : ${xpd}
  overrides: ${xp_overrides}

dm: 
  _target_: contrib.multi_domain_diag.load_cfg_from_xp
  key: datamodule
  xpd : ${xpd}
  overrides: ${xp_overrides}

ckpt:
  _target_: src.utils.best_ckpt
  xp_dir: ${xpd}/base

test_domains: ???

# test_periods: [["2012-10-22", "2012-12-02"]]
test_periods: [['2009-07-01', '2010-07-31']]

rec_weight:
  _target_: contrib.multi_domain_diag.get_smooth_spat_rec_weight
  orig_rec_weight: 
    _target_: contrib.multi_domain_diag.load_cfg_from_xp
    key: model.rec_weight
    xpd : ${xpd}

entrypoints:
  - _target_: pytorch_lightning.seed_everything
    seed: 333
  - _target_: contrib.multi_domain_diag.multi_domain_osse_diag
    trainer: ${trainer}
    lit_mod: ${lit_mod}
    dm: ${dm}
    ckpt_path: ${ckpt}
    rec_weight: ${rec_weight}
    test_domains: ${test_domains}
    test_periods: ${test_periods}
    save_dir: ${hydra:runtime.output_dir}
  # - _target_: contrib.multi_domain_diag.multi_domain_osse_metrics
  #   tdat: {_target_: contrib.multi_domain_diag.load_oi_4nadirs}
  #   test_domains: ${test_domains}
  #   test_periods: ${test_periods}

defaults:
  - /domain: qnatl
  - /domain@test_domains.qnatl: qnatl
  - /domain@test_domains.cNATL: cNATL
  - /domain@test_domains.4gf: 4gf
  - /domain@test_domains.2gf: 2gf
  - /domain@test_domains.gf: gf
  - /domain@test_domains.canaries: canaries
  - /domain@test_domains.osmosis: osmosis
  - /domain@test_domains.eNATL: eNATL
  - /domain@test_domains.NATL: NATL
  - _self_

